:rootdir: ../../..
:sourcedir: {rootdir}/src/main/java

:toc:
:numbered:
= Сервис scheduler.

== Точки входа:
* kafka
** application.yaml: `application.scheduler-service.consumer.unlock-schedulers.topic`

== Точки выхода:
* kafka
** application.yaml: `application.scheduler-service.producer.execute-external-job.topic`

== Требования:
* jdk11
* maven 3

== Сборка:
* Linux и macOS:
```
mvn clean package
```
* Windows:
```
mvn clean package
```

== Запуск:
* Linux и macOS:
```
java -jar <file.jar>
```
* Windows:
```
java -jar <file.jar>
```

== Использование:
* Настроить интеграцию со внешним сервисом
* Сконфигурировать список и параметры шедулера во внешнем ресурсе

== Общие сведения.
* Scheduler - сервис гибкой настройки, создания шедулеров. Предназначен для запланированного запуска заданий (джобов) во внешних сервисах.
* Шедулеры инициализируются при запуске приложения, конфигурация шедулеров содержится во внешнем ресурсе.
* Инициализированные шедулеры имеют запланированную задачу (джобу). В рамках сервиса Scheduler, задача шедулера - отправить команду на выполнение джобы во внешнем сервисе.
* Если параметр шедулера подразумевает ожидание исполнения задачи (например, fixedDelay шедулеры), шедулер блокируется после отправки команды на выполнение джобы во внешнем сервисе. Разблокировка происходит при получении команды на разблокировку шедулера во внешнем сервисе.

=== Интеграция с другими сервисами.
==== Интеграция посредством kafka.
* Интеграция посредством кафка используется при включенном флаге `spring.kafka.enabled` в `application.yaml`. Конфигурация kafka осуществляется через `application.yaml`.

=== Конфигурация шедулеров.
Конфигурация шедулеров содержится во внешнем ресурсе.
Сервис `SchedulersInitializationService` получает мапу с шедулерами из `SchedulerListConfigurationService`, который, в свою очередь, получает конфигурацию шедудеров из внешнего ресурса.

==== Конфигурация шедулеров в yaml-файле.
* Инициализация шедулеров посредством yaml осуществляется при включенной настройке ``application.scheduler-initialisation-type=yaml``.
* Шедулеры добавляются в `application.yaml` в раздел `schedulers` в виде списка.
* Класс, хранящий список шедулеров, получет списки с различными типами шедулеров из `application.yaml` и возвращает список пар, в которых ключом является тип шедулера, а значением - список шедулеров данного типа. При инициализации каждый тип шедулеров обрабатывается отдельно, т.к. у них могут различаться как параметры задержки (например, cron/fixedDelay), так и сама джоба (например, шедулеры типа cron не ожидают завершения джобы во внешнем сервисе и не нуждаются в проверке на блокировку).

=== Блокировка шедулеров.
Блокировка шедулеров необходима для обеспечения ожидания завершения джобы во внешнем сервисе. Состояние шедулера (заблокирован/разблокирован) хранит `SchedulerConditionService`. Шедулеры, которые нуждаются в механизме блокировки, запрашивают состояние шедулера каждый раз перед выполнением джобы и переводят шедулер в состояние "заблокирован" после отправки команды на исполнение джобы во внешнем сервисе. Блокировку снимает сообщение, отправляемое по окончании джобы внешним сервисом.
